# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- name: tag
  value: '$(Build.BuildNumber)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Publish
  jobs:  
  - job: BuildAndTest
    displayName: Build and Test .NET projects
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
        vstsFeed: '534b90ef-0e1b-475a-8b29-f869c9ffb2fd/202483c3-5d54-4aec-a875-a4bd78523c18'
        verbosityRestore: minimal
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--no-restore -v q'
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: '**/*.UnitTests.csproj'
        arguments: '--no-build'
    - task: Docker@2
      inputs:
        containerRegistry: 'PublicDockerHub'
        repository: 'maartenvana/sinance'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Sinance.Web/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(Build.BuildId)
          latest