//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finances.Web.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Finances.Web.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Datum&quot;,&quot;Naam / Omschrijving&quot;,&quot;Rekening&quot;,&quot;Tegenrekening&quot;,&quot;Code&quot;,&quot;Af Bij&quot;,&quot;Bedrag (EUR)&quot;,&quot;MutatieSoort&quot;,&quot;Mededelingen&quot;
        ///&quot;20150304&quot;,&quot;[TRANSACTION_ONE_NAME]&quot;,&quot;IBANBANKACCOUNT1&quot;,&quot;DESTINATIONACCOUNT1&quot;,&quot;IC&quot;,&quot;Af&quot;,&quot;18,69&quot;,&quot;Incasso&quot;,&quot;TestDescription1&quot;
        ///&quot;20150305&quot;,&quot;[TRANSACTION_TWO_NAME]&quot;,&quot;IBANBANKACCOUNT2&quot;,&quot;DESTINATIONACCOUNT2&quot;,&quot;BA&quot;,&quot;Af&quot;,&quot;40,17&quot;,&quot;Betaalautomaat&quot;,&quot;TestDescription2&quot;
        ///.
        /// </summary>
        internal static string INGImport {
            get {
                return ResourceManager.GetString("INGImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PictureImport {
            get {
                object obj = ResourceManager.GetObject("PictureImport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
