//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finances {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Finances.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to april.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to augustus.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschikbare kolommen.
        /// </summary>
        public static string AvailableColumnTypes {
            get {
                return ResourceManager.GetString("AvailableColumnTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er bestaat al een bankrekening met deze naam.
        /// </summary>
        public static string BankAccountAlreadyExists {
            get {
                return ResourceManager.GetString("BankAccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankrekening aangemaakt.
        /// </summary>
        public static string BankAccountCreated {
            get {
                return ResourceManager.GetString("BankAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankrekening niet gevonden.
        /// </summary>
        public static string BankAccountNotFound {
            get {
                return ResourceManager.GetString("BankAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankrekening verwijderd.
        /// </summary>
        public static string BankAccountRemoved {
            get {
                return ResourceManager.GetString("BankAccountRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankrekening aangepast.
        /// </summary>
        public static string BankAccountUpdated {
            get {
                return ResourceManager.GetString("BankAccountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie aangemaakt.
        /// </summary>
        public static string CategoryCreated {
            get {
                return ResourceManager.GetString("CategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie mapping aangemaakt.
        /// </summary>
        public static string CategoryMappingAdded {
            get {
                return ResourceManager.GetString("CategoryMappingAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie mapping is verwijderd.
        /// </summary>
        public static string CategoryMappingDeleted {
            get {
                return ResourceManager.GetString("CategoryMappingDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie mapping aangepast.
        /// </summary>
        public static string CategoryMappingEdited {
            get {
                return ResourceManager.GetString("CategoryMappingEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie mapping niet gevonden.
        /// </summary>
        public static string CategoryMappingNotFound {
            get {
                return ResourceManager.GetString("CategoryMappingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorieën toegekend aan transacties.
        /// </summary>
        public static string CategoryMappingsAppliedToTransactions {
            get {
                return ResourceManager.GetString("CategoryMappingsAppliedToTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie niet gevonden.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie verwijderd.
        /// </summary>
        public static string CategoryRemoved {
            get {
                return ResourceManager.GetString("CategoryRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie aangepast.
        /// </summary>
        public static string CategoryUpdated {
            get {
                return ResourceManager.GetString("CategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een bankrekening.
        /// </summary>
        public static string ChooseBankAccount {
            get {
                return ResourceManager.GetString("ChooseBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactie categorie kon niet gewijzigd worden.
        /// </summary>
        public static string CouldNotUpdateTransactionCategory {
            get {
                return ResourceManager.GetString("CouldNotUpdateTransactionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to december.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden tijdens het verwerken van het bestand.
        /// </summary>
        public static string ErrorWhileProcessingImport {
            get {
                return ResourceManager.GetString("ErrorWhileProcessingImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to februari.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U heeft te lang gewacht met het opslaan van de import, de import moet opnieuw uitgevoerd worden.
        /// </summary>
        public static string ImportTimeOut {
            get {
                return ResourceManager.GetString("ImportTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankrekening.
        /// </summary>
        public static string ImportToBankAccount {
            get {
                return ResourceManager.GetString("ImportToBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is vereist.
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to januari.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to juli.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to juni.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maart.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mei.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen categorie.
        /// </summary>
        public static string NoCategory {
            get {
                return ResourceManager.GetString("NoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen hoofdcategorie.
        /// </summary>
        public static string NoMainCategory {
            get {
                return ResourceManager.GetString("NoMainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen rapport gevonden.
        /// </summary>
        public static string NoReportFound {
            get {
                return ResourceManager.GetString("NoReportFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to november.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oktober.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to september.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal bedrag van categorieën is hoger dan de transactie.
        /// </summary>
        public static string TotalAmountTooHigh {
            get {
                return ResourceManager.GetString("TotalAmountTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactie toegevoegd.
        /// </summary>
        public static string TransactionAdded {
            get {
                return ResourceManager.GetString("TransactionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie voor transactie niet gevonden.
        /// </summary>
        public static string TransactionCategoryNotFound {
            get {
                return ResourceManager.GetString("TransactionCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactie verwijderd.
        /// </summary>
        public static string TransactionDeleted {
            get {
                return ResourceManager.GetString("TransactionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactie niet gevonden.
        /// </summary>
        public static string TransactionNotFound {
            get {
                return ResourceManager.GetString("TransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Transacties zijn toegevoegd, {1} transacties zijn overgeslagen.
        /// </summary>
        public static string TransactionsAddedAndSkippedFormat {
            get {
                return ResourceManager.GetString("TransactionsAddedAndSkippedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactie aangepast.
        /// </summary>
        public static string TransactionUpdated {
            get {
                return ResourceManager.GetString("TransactionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op dit moment worden alleen mappings op &quot;Omschrijving&quot;, &quot;Naam&quot; en &quot;Tegenrekening&quot; ondersteund.
        /// </summary>
        public static string UnsupportedColumnTypeMapping {
            get {
                return ResourceManager.GetString("UnsupportedColumnTypeMapping", resourceCulture);
            }
        }
    }
}
